[tasks.reboot-to-bootloader]
command = "sam"
args = ["bootloader"]
# Try to keep going, e.g. if the device already is in bootloader mode
ignore_errors = true

[tasks.build]
command = "rustup"
args = [
    "run",
    "nightly",
    "cargo",
    "build",
    "--release",
]

[tasks.test]
disabled = true

[tasks.objcopy]
command = "rustup"
args = [
    "run",
    "nightly",
    "cargo",
    "objcopy",
    "--quiet",
    "--release",
    "--",
    "-O", "binary",
    "target/thumbv7em-none-eabihf/release/dfu-rs.bin"
]
dependencies = ["build"]

[tasks.dfu]
linux_alias = "dfu_linux"
windows_alias = "dfu_win"

[tasks.dfu_linux]
command = "dfu-util"
args = [
    "-d", "0483:df11",
    "-a", "0",
    "-s", "0x08000000:leave",
    "-D", "target/thumbv7em-none-eabihf/release/dfu-rs.bin",
    "-w"
]
dependencies = ["objcopy", "reboot-to-bootloader"]

[tasks.dfu_win]
command = "./dfu-util.exe"
args = [
    "-d", "0483:df11",
    "-a", "0",
    "-s", "0x08000000:leave",
    "-D", "target/thumbv7em-none-eabihf/release/dfu-rs.bin",
]
dependencies = ["objcopy", "reboot-to-bootloader"]

[tasks.dfu-log]
command = "sam"
args = ["logcat"]
dependencies = ["dfu"]

[tasks.swd]
command = "rustup"
args = [
    "run",
    "nightly",
    "cargo",
    "embed",
    "--release",
    "--chip=stm32f401rctx"
]
